export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_CURRENT_RATES_SUCCESS = 'GET_CURRENT_RATES_SUCCESS';

export const GET_RATES_SUCCESS = 'GET_RATES_SUCCESS';
export const GET_RATES_FAIL = 'GET_RATES_FAIL';
export const GET_RATE_SUCCESS = 'GET_RATE_SUCCESS';
export const GET_RATE_FAIL = 'GET_RATE_FAIL';

export const GET_METERS_SUCCESS = 'GET_METERS_SUCCESS';
export const GET_METERS_FAIL = 'GET_METERS_FAIL';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL= 'REGISTER_FAIL';

export const CONTRACT_LENGTH_FILTER_SUCCESS = 'CONTRACT_LENGTH_FILTER_SUCCESS';
export const CONTRACT_LENGTH_FILTER_FAIL = 'CONTRACT_LENGTH_FILTER_FAIL';
export const PROVIDER_FILTER_SUCCESS = 'PROVIDER_FILTER_SUCCESS';
export const PROVIDER_FILTER_FAIL = 'PROVIDER_FILTER_FAIL';